language: node_js
sudo: required
node_js:
  - node

cache: npm

before_install:
  - chmod +x start-server.sh

before_script:
  - './start-server.sh'

script:
  - npm test

notifications:
  email:
    on_failure: change